name: molecule_env
channels:
  - defaults
  - mjohnson541
  - conda-forge
  - rmg
dependencies:
  - rdkit >=2020.03.3.0
  - cython >=0.25.2,<3
  - conda-forge::openbabel >= 3
  - cairo
  - cairocffi
  - pyrdl
  - nose
  - lpsolve55
  - quantities
  - scipy
  - scikit-learn
  - python
