name: molecule_env
channels:
  - defaults
  - rmg
  - conda-forge
dependencies:
  - rmg::rdkit >=2020.03.3.0
  - cython >=0.25.2
  - conda-forge::openbabel >= 3
  - cairo
  - cairocffi
  - rmg::pyrdl
  - nose
  - rmg::lpsolve55
  - rmg::quantities
