# For conda build
package:
  name: rmgmolecule
  version: 0.1.0

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - {{ compiler('c') }} # [unix]
  host:
    - cython >=0.25.2
    - lpsolve55
    - numpy
    - openbabel >=3
    - pyrdl
    - python {{ python }}
    - quantities
    - rdkit >=2018
    - scipy
    - scikit-learn
    - setuptools
  run:
    - cairo
    - cairocffi
    - cython >=0.25.2
    - gprof2dot
    - graphviz
    - jinja2
    - jupyter
    - lpsolve55
    - {{ pin_compatible('numpy') }}
    - openbabel >=3
    - pydot
    - pyrdl
    - python {{ python }}
    - quantities
    - rdkit >=2018
    - scikit-learn
test:
  imports:
    - molecule

about:
  home: https://github.com/ReactionMechanismGenerator/molecule
  license: MIT
  summary: "A cheminformatics program for reaction generation"
