# For conda build
package:
  name: rmgmolecule
  version: 0.3.0

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - {{ compiler('c') }} # [unix]
  host:
    - cython >=0.25.2,<3
    - lpsolve55
    - numpy
    - conda-forge::openbabel >=3
    - pyrdl
    - python
    - quantities
    - rdkit >=2020.03.3.0
    - scipy
    - scikit-learn
    - setuptools
  run:
    - cairo
    - cairocffi
    - cython >=0.25.2,<3
    - gprof2dot
    - graphviz
    - jinja2
    - jupyter
    - lpsolve55
    - {{ pin_compatible('numpy') }}
    - conda-forge::openbabel >=3
    - pydot
    - pyrdl
    - python
    - quantities
    - rdkit >=2020.03.3.0
    - scikit-learn
test:
  imports:
    - molecule
  commands:
    - python -c 'from molecule.molecule import Molecule; mol=Molecule().from_smiles("CC")'

about:
  home: https://github.com/ReactionMechanismGenerator/molecule
  license: MIT
  summary: "A cheminformatics program for reaction generation"
